### PR TITLE
Correct silkscreen, fabrication outlines and pin numbering on LTek & Gecko connectors

### PR DESCRIPTION
**Pull request by andrewteasdale**
On a recent project, I discovered (the expensive way) that the existing LTek connector footprints had an inconsistency in the silkscreen/fabrication outlines. These outlines showed the shape of the connector but this did not match the pin 1 ident. For reference, an existing footprint:

image

The product datasheet:

image

I have amended the silkscreen and fabrication layers accordingly. I have also taken the opportunity to add a second reference designator on the fabrication layer and to increase the fabrication outline from 0.05mm to 0.1mm in line with KLC guidelines. Example updated footprint:

image

Happy to discuss and make further modification as required.

### CODE REVIEW

**Comment by andrewteasdale** [comment]
I have subsequently appended _${KISYS3DMOD}_ to the model paths and made the strain relief holes NPTH [which also resolves the KLC annular ring size issue]. All checks now pass.

**Comment by andrewteasdale** [comment]
It has been pointed out to me that although the silkscreen is now correct, the pin numbering is incorrect - the manufacturer's datasheet shows e.g. pins 1-5 on row 1 and 6-10 on row 2. This is somewhat counter-intuitive and conflicts with the current pin numbering scheme [odd numbers on row 1, even numbers on row 2].

Comments welcome - I am happy to change to match the manufacturer's datasheet if this is considered to be the correct approach.

**Comment by poeschlr** [comment]
@andrewteasdale 
New connector symbols have been added to the library.
You should now be able to number the pins in the same way as the datasheet shows.
(compatible symbols: Conn_02x??_Top_Bottom)

**Comment by andrewteasdale** [comment]
Thanks @poeschlr - I'll update accordingly so the parts match the datasheet

**Comment by andrewteasdale** [comment]
Just a note on the Travis failure - the failure is on the Gecko parts, in which I have only touched the pin numbers. I'm happy to fix these pre-existing errors [F.Fab outlines and second REFDES] as part of a separate PR at a later date, as I'm also working on adding the JTek series connectors.

**Comment by poeschlr** [comment]
If you want to add a complete series of connector footprints it might be easier to use a script.
There is a good framework at https://github.com/pointhi/kicad-footprint-generator

**Comment by andrewteasdale** [comment]
@poeschlr - I have updated the Gecko parts to be KLC compliant. All parts currently in the Harwin connector library now have correct pin numbering per the manufacturer's datasheet. Below is an example of one of each connector type:

image

image

Apologies that this PR has become quite involved - I did not initially intend to make as many changes... Any further changes e.g. to include the J-Tek parts will form a separate PR. Thanks!

**Comment by poeschlr** [comment]
From the screenshot it seems there is no pin 1 marker on the fab layer. Please add one.

**Comment by andrewteasdale** [comment]
Good spot - pin-1 identifier has now been added to all connectors

**Comment by poeschlr** [comment]
Nice contribution. Thanks for your patience.

**Pull request merged**
